apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: oc-cicd-pipeline
  namespace: oc-cicd
spec:
  params:
  - name: IMAGE_NAME
    type: string
    default: image-registry.openshift-image-registry.svc:5000/oc-cicd/oc-cicd-example
  - name: GIT_REVISION
    type: string
    default: master
  - name: GIT_URL
    type: string
    default: https://github.com/zeronyk/OC_CICD
  - name: DOCKER_PATH
    type: string
    default: ./resource/Dockerfile
  - name: DOCKER_CONTEXT
    type: string
    default: ./resource/   
  - name: SERVICE_NAME
    type: string
    default: oc-cicd-service 
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-pvc
    - name: build-and-push
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/oc-cicd/oc-cicd-example
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(params.DOCKER_PATH)
        - name: CONTEXT
          value: $(params.DOCKER_CONTEXT)
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah-1-5-0
      workspaces:
        - name: source
          workspace: pipeline-pvc
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-and-push
      params:
        - name: SCRIPT
          value: |
            oc new-app $(params.IMAGE_NAME)
  workspaces:
    - name: pipeline-pvc