apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: oc-cicd-event-listener
spec:
  serviceAccountName: oc-cicd-account
  triggers:
  - name: pullrequest-build-and-deploy
    template:
     ref: oc-cicd-pipeline-template
    bindings:
     ref: oc-cicd-pipeline-binding
