apiVersion: v1
kind: ServiceAccount
metadata:
  name: oc-cicd-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oc-cicd-role
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oc-cicd-role-binding
subjects:
- kind: ServiceAccount
  name: oc-cicd-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oc-cicd-role
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: oc-cicd-event-listener
spec:
  serviceAccountName: oc-cicd-account
  triggers:
  - name: pullrequest-build-and-deploy
    template:
     ref: oc-cicd-pipeline-template
    bindings:
    - ref: oc-cicd-pipeline-binding
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: oc-cicd-event-listener
  name: oc-cicd-event-listener
spec:
  host: oc-cicd.161.156.154.27.nip.io
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: oc-cicd-event-listener
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge

  wildcardPolicy: None

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: oc-cicd-pipeline-binding
spec:
  params:
  - name: URL
    value: $(body.repository.clone_url)
  - name: REVISION
    value: $(body.pull_request.head.sha)
  - name: NAMESPACE
    value: oc-cicd
  - name: DEPLOYMENT
    value: oc-cicd
  - name: SERVICE_ACCOUNT
    value: oc-cicd-account

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: oc-cicd-pipeline-template
spec:
  params:
  - name: URL
    description: The repository url to build and deploy.
  - name: REVISION
    description: The revision to build and deploy.
  - name: NAMESPACE
    description: The namespace is used by OpenShift's internal image registry to store the built image.
  - name: DEPLOYMENT
    description: Name of the Deployment and the container name in the Deployment.
  - name: SERVICE_ACCOUNT
    description: The ServiceAccount under which to run the Pipeline.
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: oc-cicd-pipeline
    spec:
      serviceAccountName: $(params.SERVICE_ACCOUNT)
      pipelineRef:
        name: build-and-deploy-openshift
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.REVISION)
          - name: url
            value: $(params.URL)
      - name: image
        resourceSpec:
          type: image
          params:
          - name: url
            value: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/oc-cicd:$(params.REVISION)
      params:
      - name: DEPLOYMENT
        value: $(params.DEPLOYMENT)